http:
  routers:
    web-to-frontend:
      rule: "Host(`peer.cesi`)"
      service: "frontend-service"
      entryPoints:
        - "http"

    hello-world-user:
      rule: "Host(`peer.cesi`) && PathPrefix(`/`)"
      service: "user-management-service"
      entryPoints:
        - "http"

    service-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/service`)"
      service: "service-management-service"
      entryPoints:
        - "http"

    auth-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/auth`)"
      service: "user-management-service"
      entryPoints:
        - "http"

    user-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/user`)"
      service: "user-management-service"
      entryPoints:
        - "http"

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
    user-management-service:
      loadBalancer:
        servers:
          - url: "http://user-management:5000"
    service-management-service:
      loadBalancer:
        servers:
          - url: "http://service-management:5010"
    notification-service:
      loadBalancer:
        servers:
          - url: "http://notification-service:5020"
    messaging-service:
      loadBalancer:
        servers:
          - url: "http://messaging-service:5030"

