http:
  routers:
    web-to-frontend:
      rule: "Host(`peer.cesi`) && PathPrefix(`/`)"
      service: "frontend-service"
      priority: 1
      entryPoints:
        - "http"

    # hello-world-user:
    #   rule: "Host(`peer.cesi`) && PathPrefix(`/`)"
    #   service: "user-management-service"
    #   entryPoints:
    #     - "http"

    service-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/service`)"
      service: "service-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"

    auth-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/auth`)"
      service: "user-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"

    user-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/user`)"
      service: "user-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"

    avis-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/avis`)"
      service: "service-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"

    adminer-dashboard-router:
      rule: "Host(`peer.cesi`) && Path(`/adminer`)"
      service: "adminer-dashboard"
      middlewares:
        - "strip-adminer-prefix"
      entryPoints:
        - "http"

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
    user-management-service:
      loadBalancer:
        servers:
          - url: "http://user-management:5000"
    service-management-service:
      loadBalancer:
        servers:
          - url: "http://service-management:5010"
    notification-service:
      loadBalancer:
        servers:
          - url: "http://notification-service:5020"
    messaging-service:
      loadBalancer:
        servers:
          - url: "http://messaging-service:5030"
    adminer-dashboard:
      loadBalancer:
        servers:
          - url: "http://adminer:8080"

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - "/api"
    strip-adminer-prefix:
      stripPrefix:
        prefixes:
          - "/adminer"
