http:
  routers:
  # frontend routers :
    web-to-frontend:
      rule: "Host(`peer.cesi`) && !PathPrefix(`/api`)"
      service: "frontend-service"
      priority: 1
      entryPoints:
        - "http"
  
  # user-management routers :
    user-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/user`)"
      service: "user-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"
    
    auth-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/auth`)"
      service: "user-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"

    review-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/review`)"
      service: "user-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"

    sponsor-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/sponsor`)"
      service: "user-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"

  # service-management routers :
    service-router:
      rule: "Host(`peer.cesi`) && PathPrefix(`/api/service`)"
      service: "service-management-service"
      middlewares:
        - "strip-api-prefix"
      priority: 10
      entryPoints:
        - "http"

  # adminer router :
    adminer-dashboard-router:
      rule: "Host(`peer.cesi`) && Path(`/adminer`)"
      service: "adminer-dashboard"
      middlewares:
        - "strip-adminer-prefix"
      priority: 10
      entryPoints:
        - "http"

  services:
    # frontend-service:
    #   loadBalancer:
    #     servers:
    #       - url: "http://frontend:80"
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend-bis:80"
    user-management-service:
      loadBalancer:
        servers:
          - url: "http://user-management:5000"
    service-management-service:
      loadBalancer:
        servers:
          - url: "http://service-management:5010"
    notification-service:
      loadBalancer:
        servers:
          - url: "http://notification-service:5020"
    messaging-service:
      loadBalancer:
        servers:
          - url: "http://messaging-service:5030"
    adminer-dashboard:
      loadBalancer:
        servers:
          - url: "http://adminer:8080"

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - "/api"
    strip-adminer-prefix:
      stripPrefix:
        prefixes:
          - "/adminer"
